name: Bigfa

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify theme updates
        run: |
          curl --fail --request GET --header "Authorization: Bearer $SIGN" --url "https://farallon.4398929.workers.dev/update?theme=puma&version=${{ github.ref }}"
        env:
          SIGN: ${{ secrets.SIGN }}
